name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mise
        run: brew install mise

      - name: Run package checks
        run: mise run check
